workflows:
  ios_simulator_build:
    name: iOS Simulator Build
    max_build_duration: 60  # Optional: Sets a maximum build duration (in minutes)
    environment:
      flutter: stable  # Specify the Flutter version to use (optional)
    scripts:
      - name: Install dependencies
        script: flutter pub get  # Install dependencies

      - name: Build iOS for simulator
        script: flutter build ios --debug --simulator --target=lib/main.dart || ls -R  # Build for the simulator, list files on failure

      - name: Check build directory structure
        script: |
          echo "Checking build directory structure..."
          ls -R build/ios || echo "build/ios directory not found."

      - name: Create Runner.zip if build artifacts exist
        script: |
          if [ -d build/ios/iphonesimulator/Runner.app ]; then
            echo "Runner.app found. Zipping..."
            cd build/ios/iphonesimulator
            zip -r Runner.zip Runner.app
          else
            echo "Runner.app not found. Build may have failed."
            exit 1
          fi

      - name: Create artifact directory if not exists
        script: |
          echo "Checking if artifacts directory exists..."
          mkdir -p $CM_BUILD_DIR/artifacts  # Create the artifacts directory if it doesn't exist

      - name: Move Runner.zip to artifact directory
        script: |
          if [ -f build/ios/iphonesimulator/Runner.zip ]; then
            echo "Moving Runner.zip to artifacts..."
            mv build/ios/iphonesimulator/Runner.zip $CM_BUILD_DIR/artifacts/
          else
            echo "Runner.zip not found. Skipping download step."
            exit 1
          fi

      - name: Post-build step
        script: echo "Build complete. Check for Runner.zip in the artifacts section."

    artifacts:
      - $CM_BUILD_DIR/artifacts/Runner.zip  # Specify the location of the artifact
