workflows:
  ios_simulator_build:
    name: iOS Simulator Build
    max_build_duration: 60  # Optional: Sets a maximum build duration (in minutes)
    environment:
      flutter: stable  # Specify the Flutter version to use (optional)
    scripts:
      - name: Install dependencies
        script: flutter pub get  # Run 'flutter pub get' to install dependencies

      - name: Build iOS for simulator
        script: flutter build ios --debug --simulator --target=lib/main.dart  # Builds for simulator

      - name: Zip the build artifact
        script: |
          # Archive the iOS build and create a .zip file
          mkdir -p $HOME/build_output
          cp -r build/ios/iphoneos/*.app $HOME/build_output  # Copy .app file to output folder
          cd $HOME/build_output
          zip -r app_build.zip .  # Create a .zip file of the build artifact

      - name: Upload the .zip file as an artifact
        script: |
          # Codemagic automatically stores the uploaded files as artifacts
          mkdir -p $CM_BUILD_DIR/artifacts  # Create the artifacts directory if it doesn't exist
          mv $HOME/build_output/app_build.zip $CM_BUILD_DIR/artifacts  # Move the zip file to Codemagic's artifacts directory

      - name: Post-build step
        script: echo "Build complete. Artifact is ready for download."
