workflows:
  ios_simulator_build:
    name: iOS Simulator Build
    macos:
      build:
        ios:
          configuration: Debug  # Use Debug for testing
          simulator: true  # Target the iOS simulator (not a physical device)
          target: "iPhone 13"  # Specify the simulator device, like iPhone 13

    # Optionally, run tests after building the app
    scripts:
      - name: Run Tests
        script: |
          # Run Flutter tests if needed
          flutter test

    # If you want to run Flutter driver tests
    flutter_test:
      enabled: true
      test_path: "test"
