workflows:
  ios_simulator_build:
    name: iOS Simulator Build
    max_build_duration: 60  # Optional: Sets a maximum build duration (in minutes)
    steps:
      - name: Install dependencies
        flutter: install

      - name: Build iOS for simulator
        flutter: build
        args:
          ios:
            configuration: Debug  # Use Debug for testing
            simulator: true  # Target the iOS simulator (not a physical device)
            target: "iPhone 13"  # Specify the simulator device, like iPhone 13

      - name: Run tests
        script: |
          # Run Flutter tests if needed
          flutter test

    # Optionally, add post-build scripts or additional steps if needed
    post_build:
      - name: Post-build step
        script: |
          echo "Build complete, you can now upload your app to testing services"
